Update engine version

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -5,8 +5,37 @@ on:
   pull_request:
 
 jobs:
+  linux:
+    name: Linux (.NET 5)
+    runs-on: ubuntu-20.04
+
+    steps:
+      - name: Clone Repository
+        uses: actions/checkout@v2
+
+      - name: Install .NET 5
+        uses: actions/setup-dotnet@v1
+        with:
+          dotnet-version: '5.0.x'
+
+      - name: Prepare Environment
+        run: |
+          . mod.config;
+          awk '/\r$$/ { exit(1); }' mod.config || (printf "Invalid mod.config format. File must be saved using unix-style (LF, not CRLF or CR) line endings.\n"; exit 1);
+
+      - name: Check Code
+        run: |
+          make check
+          make check-packaging-scripts
+
+      - name: Check Mod
+        run: |
+          sudo apt-get install lua5.1
+          make check-scripts
+          make test
+
   linux-mono:
-    name: Linux
+    name: Linux (mono)
     runs-on: ubuntu-20.04
 
     steps:
@@ -20,29 +49,36 @@ jobs:
 
       - name: Check Code
         run: |
-          make check
+          # check-packaging-scripts does not depend on .net/mono, so is not needed here
+          mono --version
+          make RUNTIME=mono check
 
       - name: Check Mod
         run: |
-          sudo apt-get install lua5.1
-          make check-scripts
-          make test
+          # check-scripts does not depend on .net/mono, so is not needed here
+          make RUNTIME=mono test
 
   windows:
-    name: Windows
+    name: Windows (.NET 5.0)
     runs-on: windows-2019
 
     steps:
       - name: Clone Repository
         uses: actions/checkout@v2
 
+      - name: Install .NET 5
+        uses: actions/setup-dotnet@v1
+        with:
+          dotnet-version: '5.0.x'
+
       - name: Check Code
         shell: powershell
         run: |
+          # Work around runtime failures on the GH Actions runner
           dotnet nuget locals all --clear
           .\make.ps1 check
 
-      - name: Check Mod
+      - name: Check Mods
         run: |
           chocolatey install lua --version 5.1.5.52
           $ENV:Path = $ENV:Path + ";C:\Program Files (x86)\Lua\5.1\"
